### PR TITLE
Minimal operative version

### PR DESCRIPTION
**Pull request by alecandido**

### CODE REVIEW

**Review by cschwan — COMMENTED** [review]
General comments:

- Do we really need a CLI? Cache management can be done with your favourite file manager, configuration file management with your favourite editor and the only reason I see is to list all available PDF sets. However I'd drop the CLI for the time being for simplicity's sake
- I strongly suggest we get rid of all mention to `async`. As far as I understand we need to get some data from disk/network, and then the main job interpolation. These two jobs are strongly ordered, so I don't see the value of `async`, especially when the tokio crate is so heavy.
- We should also get completely rid of the LHAPDF code that duplicates the `lhapdf` create.
- For the time being error handling with `anyhow` is OK, but as soon as the API stabilizes somewhat we should create a single or a few error structs with `thiserror`.
- more comments soon ...

**Comment by alecandido** [comment]
> * Do we really need a CLI? Cache management can be done with your favourite file manager, configuration file management with your favourite editor and the only reason I see is to list all available PDF sets. However I'd drop the CLI for the time being for simplicity's sake

I get your point, and having less code is for sure helpful to speed up the development of the core.

On the other hand, I believe we might need a minimal one, at least from a sociological point of view. This because LHAPDF has it, and for most of the people (even within NNPDF) it would be simpler to have a closer workflow, even though it's not strictly required.
So, I thought it would be facilitating adoption.

But I'm open to discussion on this.

**Comment by alecandido** [comment]
> * I strongly suggest we get rid of all mention to `async`. As far as I understand we need to get some data from disk/network, and then the main job interpolation. These two jobs are strongly ordered, so I don't see the value of `async`, especially when the tokio crate is so heavy.

About this point I fully agree. The main reason for `async` was to download many sets at once, filing multiple requests altogether. But if you want to download a massive amount of data, it's sensible to take some more time, and the server should impose a rate limit anyhow...

I would merge this *as is*: since it's just working, I want to merge without major changes.
But I'll make a further PR soon to go for a fully blocking interface, dropping Tokio dependency (I was right now thinking to best way to expose *also* a blocking interface, but *only* is just better).

Notice that the runtime will still be around anyhow, because `reqwest` is asynchronous itself. But at least we don't have to deal with `async` ourselves, since we'll use the blocking `reqwest` interface it will be up to them.

**Comment by alecandido** [comment]
> We should also get completely rid of the LHAPDF code that duplicates the `lhapdf` create.

I guess you refer to your own [`lhapdf` *crate*](https://github.com/cschwan/lhapdf/). But for that's just one file, i.e. [`lib.rs`](https://github.com/cschwan/lhapdf/blob/master/src/lib.rs), and mostly made of bindings, that I definitely do not want to use, since one of the main goals was fully getting rid of LHAPDF dependency (even in the handling of LHAPDF files).
I'd keep the `lhapdf` crate only for benchmarks (and so within `[dev-dependencies]` section).


> * For the time being error handling with `anyhow` is OK, but as soon as the API stabilizes somewhat we should create a single or a few error structs with `thiserror`.

Agreed: `thiserror` > `anyhow` > `unwrap`. For the time being I just wanted a quick enough option.

**Comment by cschwan** [comment]
> On the other hand, I believe we might need a minimal one, at least from a sociological point of view. This because LHAPDF has it, and for most of the people (even within NNPDF) it would be simpler to have a closer workflow, even though it's not strictly required. So, I thought it would be facilitating adoption.

That's good point, people are probably expecting it.

**Comment by cschwan** [comment]
> I would merge this _as is_: since it's just working, I want to merge without major changes. But I'll make a further PR soon to go for a fully blocking interface, dropping Tokio dependency (I was right now thinking to best way to expose _also_ a blocking interface, but _only_ is just better).

:+1:

> 
> Notice that the runtime will still be around anyhow, because `reqwest` is asynchronous itself. But at least we don't have to deal with `async` ourselves, since we'll use the blocking `reqwest` interface it will be up to them.

There's a blocking interface of [`reqwest`](https://docs.rs/reqwest/latest/reqwest/blocking/index.html) with which we can limit the number of tokio dependencies; instead of `tokio[full]` we'd only indirectly depend on `tokio[sync]`.

**Comment by cschwan** [comment]
> > We should also get completely rid of the LHAPDF code that duplicates the `lhapdf` create.
> 
> I guess you refer to your own [`lhapdf` _crate_](https://github.com/cschwan/lhapdf/). But for that's just one file, i.e. [`lib.rs`](https://github.com/cschwan/lhapdf/blob/master/src/lib.rs), and mostly made of bindings, that I definitely do not want to use, since one of the main goals was fully getting rid of LHAPDF dependency (even in the handling of LHAPDF files). I'd keep the `lhapdf` crate only for benchmarks (and so within `[dev-dependencies]` section).

No I meant the code that I wrote in `partons`, but maybe you've already deleted it. In any case, the latter you wrote is how I'd thought about it as well.

> 
> > * For the time being error handling with `anyhow` is OK, but as soon as the API stabilizes somewhat we should create a single or a few error structs with `thiserror`.
> 
> Agreed: `thiserror` > `anyhow` > `unwrap`. For the time being I just wanted a quick enough option.

:+1:

**Comment by alecandido** [comment]
> That's good point, people are probably expecting it.

In any case, from my point of view, the CLI will be just a thin wrapper over library functions. I don't want even the nice tables of PineAPPL, just lines (such that they can be processed with standard GNU utilities), or JSON for structured data (that can be processed with `jq`).
Anything that is available to CLI, should also be available in the library, with a single call (if possible).

> There's a blocking interface of [`reqwest`](https://docs.rs/reqwest/latest/reqwest/blocking/index.html) with which we can limit the number of tokio dependencies; instead of `tokio[full]` we'd only indirectly depend on `tokio[sync]`.

You're right, way better!

> No I meant the code that I wrote in `partons`, but maybe you've already deleted it. In any case, the latter you wrote is how I'd thought about it as well.

Currently, it's still in the branch, but in a separate folder (not under `src`, but the `lhapdf` sibling).
At the beginning, I wanted to continue the idea of the multiple back-ends. But in the end, I wanted a fully separate one, and I don't want to really have different back-ends at runtime, to lower the complication (and avoid the linked dependency, even if feature gated).

But I'd like to keep that code, for the benchmarks, since I want to make sure to generate the same values of LHAPDF in the interpolation regime (in principle, we should be applying the same float operations, so we might be able to agree at float precision).

**Comment by cschwan** [comment]
OK, then we agree how to proceed and you should merge this PR!

**Pull request merged**
